#!/bin/bash

LOG_LEVEL=${LOG_LEVEL:-0}
[ $LOG_LEVEL -ge 2 ] && set -x

# randomize in order to avoid too many concurrent connection to kubeapi

sleep $((RANDOM % 15))

version=$(curl -sk https://kubernetes.default.svc.cluster.local/version | jq '"\(.major).\(.minor)"' -r | grep -o '[0-9\.]\+')

if [ -x /usr/local/bin/kubectl-v${version} ]; then
  ln -fs /usr/local/bin/kubectl-v${version} /usr/local/bin/kubectl
fi

NODE_ROLE=node
NODE_NAME=$(kubectl get pod -n $NAMESPACE $POD_NAME -o json | jq -r .spec.nodeName)
NODE=$(kubectl get node $NODE_NAME -o json)

# Discovery node role
HAS=$(echo "$NODE" | jq -r '.metadata.labels | has("node-role.kubernetes.io/controlplane")')
if [ "$HAS" == true ]; then
  NODE_LABEL=node-role.kubernetes.io/controlplane=$(echo "$NODE" | jq -r '.metadata.labels["node-role.kubernetes.io/controlplane"]')
  NODE_ROLE=controlplane
else
  HAS=$(echo "$NODE" | jq -r '.metadata.labels | has("node-role.kubernetes.io/master")')
  if [ "$HAS" == true ]; then
    NODE_LABEL=node-role.kubernetes.io/master=$(echo "$NODE" | jq -r '.metadata.labels["node-role.kubernetes.io/master"]')
    NODE_ROLE=controlplane
  fi
fi

file=${VALUES_FILE:-/data/values.yaml}
dir=${file%/*}
mkdir -p $dir

/certificate-discovery $ROOT $NODE_ROLE $NODE_LABEL > $file

if [ $LOG_LEVEL -ge 1 ]; then
  echo Created $file
  echo ---
  cat $file
  echo ---
fi

# Create the configmaps to be used by helm to install x509-certificates-exporter
# they are going to be overwriten for each node where this code runs, but thats not a problem because the results should be the same.

CONFIGMAP_NAME=$(printf -- "${CONFIGMAP_NAME_FMT:-%s}" $NODE_ROLE)
kubectl create configmap -n ${CONFIGMAP_NAMESPACE:-$NAMESPACE} $CONFIGMAP_NAME --from-file=${file} --dry-run=client -o yaml | kubectl apply -f -

# Restart after some time because some OKD controlplane pods may have being updates, incrementing its revision number.
FREQUENCY_HOURS=${FREQUENCY_HOURS:-24}
echo
echo Will run again $(date --utc --date="now + $FREQUENCY_HOURS hours")

sleep ${FREQUENCY_HOURS}h
exec "$0" "$@"
